CREATE DATABASE sampleDB;
USE sampleDB;
CREATE TABLE CUSTOMERS (
ID INT  NOT NULL,
NAME VARCHAR (20) NOT NULL,
AGE INT  NOT NULL,
ADDRESS CHAR (25),
SALARY DECIMAL (18,2),
PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS VALUES
(1, 'Ramesh', 32, 'Almedabad', 2000.00),
(2, 'Khilan', 25, 'Dehli', 1500),
(3, 'kaushik', 23, 'Kota', 2000),
(4, 'Chaitali', 25, 'Mumbai', 6500),
(5, 'Hardik', 27, 'Bhopal', 8500),
(6, 'Komal', 22, 'Hyderabad', 4500),
(7, 'Muffy', 24, 'Indore', 10000);

SELECT * FROM CUSTOMERS;
ALTER TABLE CUSTOMERS ADD SEX char(1);
SELECT DISTINCT SALARY FROM CUSTOMERS ORDER BY SALARY;

SELECT ID, NAME, SALARY
FROM CUSTOMERS
WHERE SALARY > 2000;

SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 AND AGE < 25;

SELECT * FROM CUSTOMERS
WHERE NAME IN ('Khilan', 'Hardik', 'Muffy');

SELECT * FROM CUSTOMERS WHERE AGE BETWEEN 20 AND 25;

SELECT * FROM CUSTOMERS WHERE SALARY LIKE '200%';

SELECT * FROM CUSTOMERS ORDER BY NAME ASC;

SELECT * FROM CUSTOMERS ORDER BY NAME DESC;

SELECT ADDRESS, AGE, SUM(SALARY)
AS TOTAL_SALARY FROM CUSTOMERS
GROUP BY ADDRESS, AGE;

SELECT AGE, COUNT(NAME) FROM CUSTOMERS GROUP BY AGE;

SELECT ADDRESS, AGE, SUM(SALARY) AS TOTAL_SALARY FROM CUSTOMERS GROUP BY ADDRESS, AGE HAVING TOTAL_SALARY >=5000
ORDER BY TOTAL_SALARY DESC;